version: "3.8"

name: film-service

services:
  nginx:
    image : "nginx:stable-alpine"
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../:/var/www
    working_dir: /var/www/
#    For linux
#    extra_hosts:
#      - host.docker.internal:host-gateway


  mysql:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./database:/var/lib/mysql
      - ./scripts/tables.sql:/docker-entrypoint-initdb.d/0_init.sql

  composer:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../:/var/www
    entrypoint:
      [ 'composer', '--ignore-platform-reqs' ]